
package com.camaradirecta.rue.MR01D;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MR01DDelegate", targetNamespace = "urn:RUE:RUE_WebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MR01DDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.camaradirecta.rue.MR01D.RueLiquidacionBC
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitudLiquidacion", targetNamespace = "urn:RUE:RUE_WebService", className = "com.camaradirecta.rue.MR01D.SolicitudLiquidacion")
    @ResponseWrapper(localName = "solicitudLiquidacionResponse", targetNamespace = "urn:RUE:RUE_WebService", className = "com.camaradirecta.rue.MR01D.SolicitudLiquidacionResponse")
    public RueLiquidacionBC solicitudLiquidacion(
        @WebParam(name = "arg0", targetNamespace = "")
        RueLiquidacionBC arg0);

}
