
package com.camaradirecta.rue.MR01D;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MR01D", targetNamespace = "urn:RUE:RUE_WebService", wsdlLocation = "http://tomcat2.camaradirecta.com:8080/registroWeb/service/MR01D.asmx?wsdl")
public class MR01D
    extends Service
{

    private final static URL MR01D_WSDL_LOCATION;
    private final static WebServiceException MR01D_EXCEPTION;
    private final static QName MR01D_QNAME = new QName("urn:RUE:RUE_WebService", "MR01D");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tomcat2.camaradirecta.com:8080/registroWeb/service/MR01D.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MR01D_WSDL_LOCATION = url;
        MR01D_EXCEPTION = e;
    }

    public MR01D() {
        super(__getWsdlLocation(), MR01D_QNAME);
    }

    public MR01D(WebServiceFeature... features) {
        super(__getWsdlLocation(), MR01D_QNAME, features);
    }

    public MR01D(URL wsdlLocation) {
        super(wsdlLocation, MR01D_QNAME);
    }

    public MR01D(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MR01D_QNAME, features);
    }

    public MR01D(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MR01D(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MR01DDelegate
     */
    @WebEndpoint(name = "MR01D")
    public MR01DDelegate getMR01D() {
        return super.getPort(new QName("urn:RUE:RUE_WebService", "MR01D"), MR01DDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MR01DDelegate
     */
    @WebEndpoint(name = "MR01D")
    public MR01DDelegate getMR01D(WebServiceFeature... features) {
        return super.getPort(new QName("urn:RUE:RUE_WebService", "MR01D"), MR01DDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MR01D_EXCEPTION!= null) {
            throw MR01D_EXCEPTION;
        }
        return MR01D_WSDL_LOCATION;
    }

}
