com:
  camaradirecta:
    app:
      rues:
        token:
          username: RUESBucaramanga
          password: Webapi2017*
          grant_type: password
          url: https://pruebasruesapi.rues.org.co/Token
        RR18N:
          url-palabra-clave: https://pruebasruesapi.rues.org.co/api/ConsultaEntidades/consultarPalabraClave
          url-consultar-nombre: https://pruebasruesapi.rues.org.co/api/ConsultaEntidades/consultarNombre
          url-consultar-matricula: https://pruebasruesapi.rues.org.co/api/ConsultaEntidades/consultarMatricula
          url-consultar-homonimia: https://pruebasruesapi.rues.org.co/api/ConsultaEntidades/consultarHomonimia
          url-consultar-numero-identificacion: https://pruebasruesapi.rues.org.co/api/ConsultaEntidades/consultarNumeroIdentificacion
          