spring:
  profiles:
    active: 'dev'
  application:
    name: ccb-rues-services
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
server:
  port: ${PORT:11102}
  tomcat:
    relaxed-path-chars: <,>,[,\,],^,`,{,|,}
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}

  