com:
  camaradirecta:
    app:
      ubicacion:
        certificados: /opt/certificados-rues/
      rues:
        token:
          username: RUESBucaramanga
          password: Webapi2017*
          grant_type: password
          url: https://ruesapi.rues.org.co/Token
        RR18N:
          url-palabra-clave: https://ruesapi.rues.org.co/api/ConsultaEntidades/consultarPalabraClave
          url-consultar-nombre: https://ruesapi.rues.org.co/api/ConsultaEntidades/consultarNombre
          url-consultar-matricula: https://ruesapi.rues.org.co/api/ConsultaEntidades/consultarMatricula
          url-consultar-homonimia: https://ruesapi.rues.org.co/api/ConsultaEntidades/consultarHomonimia
          url-consultar-numero-identificacion: https://ruesapi.rues.org.co/api/ConsultaEntidades/consultarNumeroIdentificacion
        MR01D: 
          url-solicitud-liquidacion: https://ruesapi.rues.org.co/api/Liquidacion/solicitudLiquidacion
        MR02N:
          url-solicitud-radicacion: https://ruesapi.rues.org.co/api/Radicacion/solicitudRadicacion
        RR04N:
          url-solicitud-certificado: https://ruesapi.rues.org.co/api/Certificado/solicitudCertificado
        MR03N:
          url-solicitud-actualiza-estado: https://ruesapi.rues.org.co/api/Estados/solicitudActualizacionEstado
        RR31N:
          url-reporte-contratos: https://ruesapi.rues.org.co/api/Proponente/ReporteContratos
          url-reporte-multas: https://ruesapi.rues.org.co/api/Proponente/ReporteMultas
          url-reporte-sanciones: https://ruesapi.rues.org.co/api/Proponente/ReporteSanciones
          url-historico-proponente: https://ruesapi.rues.org.co/api/Proponente/v2/consultaHistoriaProponente
          url-actualizar-experiencia: https://ruesapi.rues.org.co/api/Proponente/ActualizarProponenteExperiencia
          url-actualizar-kardex: https://ruesapi.rues.org.co/api/Proponente/ActualizarProponenteKardex
          url-actualizar-san-dis: https://ruesapi.rues.org.co/api/Proponente/ActualizarProponenteSanDis
        RR09N:
          url-proponente-nit: https://ruesapi.rues.org.co/api/Proponente/ConsultaProponenteNit
          url-radicar-noticia-proponente: https://ruesapi.rues.org.co/api/Proponente/radicarNoticiasProponente
        RR30N:
          url-radicar-registro-proponente: https://ruesapi.rues.org.co/api/Proponente/ActualizarProponente
        service:
          url-service-MR03N: http://tomcat.camaradirecta.com:8080/registroWeb/service/MR03N.asmx
          url-service-MR01D: http://tomcat.camaradirecta.com:8080/registroWeb/service/MR01D.asmx
          url-service-MR02N: http://tomcat.camaradirecta.com:8080/registroWeb/service/MR02N.asmx
          url-service-RR04N: http://tomcat.camaradirecta.com:8080/registroWeb/service/RR04N.asmx
          
      