
package com.camaradirecta.rue.MR02N;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MR02N", targetNamespace = "urn:RUE:RUE_WebService", wsdlLocation = "http://tomcat2.camaradirecta.com:8080/registroWeb/service/MR02N.asmx?wsdl")
public class MR02N
    extends Service
{

    private final static URL MR02N_WSDL_LOCATION;
    private final static WebServiceException MR02N_EXCEPTION;
    private final static QName MR02N_QNAME = new QName("urn:RUE:RUE_WebService", "MR02N");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tomcat2.camaradirecta.com:8080/registroWeb/service/MR02N.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MR02N_WSDL_LOCATION = url;
        MR02N_EXCEPTION = e;
    }

    public MR02N() {
        super(__getWsdlLocation(), MR02N_QNAME);
    }

    public MR02N(WebServiceFeature... features) {
        super(__getWsdlLocation(), MR02N_QNAME, features);
    }

    public MR02N(URL wsdlLocation) {
        super(wsdlLocation, MR02N_QNAME);
    }

    public MR02N(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MR02N_QNAME, features);
    }

    public MR02N(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MR02N(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MR02NDelegate
     */
    @WebEndpoint(name = "MR02N")
    public MR02NDelegate getMR02N() {
        return super.getPort(new QName("urn:RUE:RUE_WebService", "MR02N"), MR02NDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MR02NDelegate
     */
    @WebEndpoint(name = "MR02N")
    public MR02NDelegate getMR02N(WebServiceFeature... features) {
        return super.getPort(new QName("urn:RUE:RUE_WebService", "MR02N"), MR02NDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MR02N_EXCEPTION!= null) {
            throw MR02N_EXCEPTION;
        }
        return MR02N_WSDL_LOCATION;
    }

}
