
package com.camaradirecta.rue.MR02N;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MR02NDelegate", targetNamespace = "urn:RUE:RUE_WebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MR02NDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.camaradirecta.rue.MR02N.RueRadicacionBC
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitudRadicacion", targetNamespace = "urn:RUE:RUE_WebService", className = "com.camaradirecta.rue.MR02N.SolicitudRadicacion")
    @ResponseWrapper(localName = "solicitudRadicacionResponse", targetNamespace = "urn:RUE:RUE_WebService", className = "com.camaradirecta.rue.MR02N.SolicitudRadicacionResponse")
    public RueRadicacionBC solicitudRadicacion(
        @WebParam(name = "arg0", targetNamespace = "")
        RueRadicacionBC arg0);

}
