
package com.camaradirecta.rue.RR04N;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RR04NDelegate", targetNamespace = "urn:RUE:RUE_WebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RR04NDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.camaradirecta.rue.RR04N.RueCertificadoBC
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitudCertificado", targetNamespace = "urn:RUE:RUE_WebService", className = "com.camaradirecta.rue.RR04N.SolicitudCertificado")
    @ResponseWrapper(localName = "solicitudCertificadoResponse", targetNamespace = "urn:RUE:RUE_WebService", className = "com.camaradirecta.rue.RR04N.SolicitudCertificadoResponse")
    public RueCertificadoBC solicitudCertificado(
        @WebParam(name = "arg0", targetNamespace = "")
        RueRadicacionBC arg0);

}
