
package com.camaradirecta.rue.RR04N;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RR04N", targetNamespace = "urn:RUE:RUE_WebService", wsdlLocation = "http://tomcat2.camaradirecta.com:8080/registroWeb/service/RR04N.asmx?wsdl")
public class RR04N
    extends Service
{

    private final static URL RR04N_WSDL_LOCATION;
    private final static WebServiceException RR04N_EXCEPTION;
    private final static QName RR04N_QNAME = new QName("urn:RUE:RUE_WebService", "RR04N");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tomcat2.camaradirecta.com:8080/registroWeb/service/RR04N.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RR04N_WSDL_LOCATION = url;
        RR04N_EXCEPTION = e;
    }

    public RR04N() {
        super(__getWsdlLocation(), RR04N_QNAME);
    }

    public RR04N(WebServiceFeature... features) {
        super(__getWsdlLocation(), RR04N_QNAME, features);
    }

    public RR04N(URL wsdlLocation) {
        super(wsdlLocation, RR04N_QNAME);
    }

    public RR04N(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RR04N_QNAME, features);
    }

    public RR04N(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RR04N(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RR04NDelegate
     */
    @WebEndpoint(name = "RR04N")
    public RR04NDelegate getRR04N() {
        return super.getPort(new QName("urn:RUE:RUE_WebService", "RR04N"), RR04NDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RR04NDelegate
     */
    @WebEndpoint(name = "RR04N")
    public RR04NDelegate getRR04N(WebServiceFeature... features) {
        return super.getPort(new QName("urn:RUE:RUE_WebService", "RR04N"), RR04NDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RR04N_EXCEPTION!= null) {
            throw RR04N_EXCEPTION;
        }
        return RR04N_WSDL_LOCATION;
    }

}
