
package com.camaradirecta.rue.MR03N;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MR03N", targetNamespace = "urn:RUE:RUE_WebService", wsdlLocation = "http://tomcat2.camaradirecta.com:8080/registroWeb/service/MR03N.asmx?wsdl")
public class MR03N
    extends Service
{

    private final static URL MR03N_WSDL_LOCATION;
    private final static WebServiceException MR03N_EXCEPTION;
    private final static QName MR03N_QNAME = new QName("urn:RUE:RUE_WebService", "MR03N");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tomcat2.camaradirecta.com:8080/registroWeb/service/MR03N.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MR03N_WSDL_LOCATION = url;
        MR03N_EXCEPTION = e;
    }

    public MR03N() {
        super(__getWsdlLocation(), MR03N_QNAME);
    }

    public MR03N(WebServiceFeature... features) {
        super(__getWsdlLocation(), MR03N_QNAME, features);
    }

    public MR03N(URL wsdlLocation) {
        super(wsdlLocation, MR03N_QNAME);
    }

    public MR03N(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MR03N_QNAME, features);
    }

    public MR03N(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MR03N(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MR03NDelegate
     */
    @WebEndpoint(name = "MR03N")
    public MR03NDelegate getMR03N() {
        return super.getPort(new QName("urn:RUE:RUE_WebService", "MR03N"), MR03NDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MR03NDelegate
     */
    @WebEndpoint(name = "MR03N")
    public MR03NDelegate getMR03N(WebServiceFeature... features) {
        return super.getPort(new QName("urn:RUE:RUE_WebService", "MR03N"), MR03NDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MR03N_EXCEPTION!= null) {
            throw MR03N_EXCEPTION;
        }
        return MR03N_WSDL_LOCATION;
    }

}
